# SPDX-License-Identifier: MPL-2.0
# Documentation repo: the only dependencies are the pinned GitHub Actions.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
